export const loginStyle = {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "380px",
    minHeight: "420px",
    bgcolor: "background.paper",
    border: "none",
    borderRadius: "8px",
    boxShadow: 24,
    pt: 4,
    pb: 2,
    px: 4,
    outline: "none",
    transition: "all 0.5s ease-in-out",
    display:"flex",
    flexDirection:"column",
    justifyContent:"space-between",
}